name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 91.98.232.237
          username: projects
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            if [ ! -d /var/www/drawtomata/.git ]; then
              rm -rf /var/www/drawtomata
              git clone https://github.com/goerll/drawtomata.git /var/www/drawtomata
            fi
            cd /var/www/drawtomata
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm build
            rm -rf dist && mv build dist